{ config, lib, pkgs, ... }:

{
  home.username = "reikimann";
  home.homeDirectory = "/home/reikimann";
  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "23.11";

  targets.genericLinux.enable = true;
  xdg.systemDirs.data = [ "${config.home.homeDirectory}/.nix-profile/share/applications" ];

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    # Fun:
    neo-cowsay
    lolcat
    fortune
    asciiquarium-transparent
    sl
    hollywood
    neofetch

    # File management
    gdu
    duf
    xdg-ninja

    # Terminal
    tmux
    yt-dlp
    bat
    eza

    # School
    teams-for-linux
    minder

    # Sysops
    rpi-imager

    # Networking
    nmap

    # Other
    rofi-wayland

    # # It is sometimes useful to fine-tune packages, for example, by applying
    # # overrides. You can do that directly here, just don't forget the
    # # parentheses. Maybe you want to install Nerd Fonts with a limited number of
    # # fonts?
    # (pkgs.nerdfonts.override { fonts = [ "FantasqueSansMono" ]; })

    # # You can also create simple shell scripts directly inside your
    # # configuration. For example, this adds a command 'my-hello' to your
    # # environment:
    # (pkgs.writeShellScriptBin "my-hello" ''
    #   echo "Hello, ${config.home.username}!"
    # '')
  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. If you don't want to manage your shell through Home
  # Manager then you have to manually source 'hm-session-vars.sh' located at
  # either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/reikimann/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    EDITOR = "nvim";
  };

  i18n.glibcLocales = pkgs.glibcLocales.override {
      allLocales = false;
      locales = [ "en_DK.UTF-8/UTF-8" ];
  };

  programs = {
    home-manager.enable = true;

    zsh = {
      enable = true;
      # TODO: Finish converting
      autocd = true;
      defaultKeymap = "viins";

      syntaxHighlighting = {
        enable = true;
      };
      enableAutosuggestions = true;
      enableCompletion = true;

      history = {
        ignoreDups = true; # TODO: true by default. Do I even need it?
        save = 512;
      };

      dotDir = ".config/zsh";
    };

    # TODO: Don't want to include email, but its not working otherwise.
    # Setup ssh instead.
    git = {
      enable = true;
      userName = "Reikimann";
      extraConfig = {
        init.defaultBranch = "main";
        credential.helper = "store --file ~/.config/git/.git-credentials";
        safe.directory = "/opt/flutter";
      };
    };

    zoxide = {
      enable = true;
      enableZshIntegration = true;
    };

    # TODO: Find a way to include the configuration
    starship = {
      enable = true;
      enableZshIntegration = true; # Not working: Zsh config not generated by home-manager
    };

    # Config not done
    # rofi = {
    #   enable = true;
    #   package = pkgs.rofi-wayland;
    # };

    # TODO:
    # btop
  };

  nix = {
    package = pkgs.nix;
    settings.experimental-features = [ "nix-command" "flakes" ];
  };
}
