[manager]
prepend_keymap = [
  { on = [ "g", "p"], run = "cd ~/pix", desc = "Goto pictures" },
  { on = [ "g", "c"], run = "cd ~/cornFlakes", desc = "Goto cornFlakes" },
  { on = [ "g", "d"], run = "cd ~/dox", desc = "Goto documents" },
  { on = [ "g", "D"], run = "cd ~/dl", desc = "Goto downloads" },
]
