{ pkgs, ... }:
{
  programs = {
    zsh = {
      enable = true;
      # TODO: Finish converting
      autocd = true;
      defaultKeymap = "viins";

      syntaxHighlighting = {
        enable = true;
      };

      shellAliases = (import ../aliases.nix).myAliases;

      autosuggestion.enable = true;
      enableCompletion = true;

      history = {
        ignoreDups = true; # TODO: true by default. Do I even need it?
        save = 512;
      };

      dotDir = ".config/zsh";
    };

    zoxide = {
      enable = true;
      enableZshIntegration = true;
    };

    # TODO: Find a way to include the configuration
    starship = {
      enable = true;
      enableZshIntegration = true; # Not working: Zsh config not generated by home-manager
    };
  };
}
